---
title: "NCI and BUN for predicting SAP patients"
format:
  docx:
    fig-dpi: 600
    fig-align: center
    fig-format: jpeg
    fig-height: 5
    fig-width: 7
execute:
  echo: false
  warning: false
  message: false
  fig-path:
knitr:
  opts_chunk:
    fig.path: "figures/"
---

```{r}
#| message: false
#| warning: false

library(randomForest)
library(gtsummary)
library(pROC)
library(rsample)
library(ggplot2)
library(ggsci)
library(rms)
library(dcurves)
library(survival)
library(tidyverse)
library(Hmisc)
library(readxl)
library(tidymodels)
library(janitor)
library(caret)
library(ggcorrplot)
library(ggpubr)
library(fastshap)
library(shapviz)
library(patchwork)

train <- read_xlsx("data/train.xlsx")
test <- read_xlsx("data/test.xlsx", sheet = "data")
```

## Process data

```{r}
train <- train %>% clean_names()
test <- test %>% clean_names()

## Training dataset
train <- train %>%
  mutate(
    sap = ifelse(mucdonang2==1, 1, 0), #1 Nặng, 0 Không nặng
    sex = ifelse(gioi=="Nam", "Male", "Female"),
    pe = ifelse(trandichmangphoi=="có", "Yes", "No"),
    bun = bu_nvv,
    lv_bisap = ifelse(diem_bisap>=3, ">=3", "<3"),
    etiology = case_when(
      nguyennhan == "Rượu" ~ "Alcohol",
      nguyennhan == "Sỏi mật" ~ "Gallstones",
      nguyennhan == "Tăng triglycerid" ~ "Triglycerid",
      TRUE ~ "Unknown"
    ),
    hbp = ifelse(tanghuyetap=="có", "Yes", "No"),
    diabetes = ifelse(daithaoduong=="có", "Yes", "No"),
    pseudocyst = ifelse(nanggiatuy==1, "Yes", "No"), #7NA
    necrosis = ifelse(tudichhoaitucaptinh==1, "Yes", "No"),#7NA
    fluid = ifelse(tudichquanhtuy=="có", "Yes", "No"),
    necrosis_wall = ifelse(hoaituthanhhoa==2, "No", "Yes"), #7NA
    mortality = ifelse(ketcuclamsang==1, "Yes", "No")) %>% 
  rename(age = tuoi,
         bisap = diem_bisap,
         lym = lymphocytevvx109l,
         wbc = bachcauvvx109l,
         hct = hc_tvv,
         lipase = lipasevv,
         neu = neutrophilvvx109l,
         plt = tieucauvv_gl,
         cre = creatininvv,
         crp = cr_pvv,
         amylase = amlasevv,
         tri = trygliceridvv,
         ctsi = d_iem_ctsi) %>% 
  select(sap, sex, age, pe, bun, bisap, lv_bisap, etiology,
         hbp, diabetes, pseudocyst, necrosis, fluid, necrosis_wall,
         mortality, lym, wbc, hct, lipase, neu, cre, amylase,
         tri, ctsi, crp, plt)

## Testing dataset
test <- test %>% 
  mutate(
    sap = ifelse(mucdonang=="NẶNG", 1, 0),
    sex = ifelse(gioi=="Nam", "Male", "Female"),
    pe = case_when(
      xq_trandichmangphoi %in% c("có", "Có") ~ "Yes",
      TRUE ~ "No"
    ),
    bun = cls_bunvv,
    lv_bisap = ifelse(bisap>=3, ">=3", "<3"),
    etiology = case_when(
      nguyennhan == "Rượu" ~ "Alcohol",
      nguyennhan == "Sỏi" ~ "Gallstones",
      nguyennhan == "Tăng TG" ~ "Triglycerid",
      TRUE ~ "Unknown"
      ),
    hbp = ifelse(h_tanghuyetap=="Có", "Yes", "No"),
    diabetes = ifelse(h_daithaoduong=="Có", "Yes", "No"),
    pseudocyst = ifelse(bctc_nanggiatuy=="Có", "Yes", "No"), 
    necrosis = ifelse(bctc_tudichhoaitucaptinh=="Có", "Yes", "No"),
    fluid = ifelse(bctc_tudichquanhtuy=="Có", "Yes", "No"),
    necrosis_wall = ifelse(bctc_hoaitutthanhhoa=="Có", "Yes", "No"),
    mortality = ifelse(ketcuc=="xuất viện", "No", "Yes")) %>% 
  rename(age = tuoi,
         lym = lymvv,
         wbc = cls_wbcvv,
         hct = cls_hct_vv,
         lipase = cls_lipasevv,
         neu = neuvv,
         plt = cls_pl_tvv,
         cre = cls_creatininvv,
         crp = cr_pvv,
         amylase = cls_amylasevv,
         tri = cls_triglyceridvv,
         ctsi = diem_ctsi) %>% 
  select(sap, sex, age, pe, bun, bisap, lv_bisap, etiology, 
         hbp, diabetes, pseudocyst, necrosis, fluid, necrosis_wall,
         mortality, lym, wbc, hct, lipase, neu, cre, amylase,
         tri, ctsi, crp, plt)
```

```{r}
external <- read_excel("data/external.xls")

external <- external %>% 
  mutate(etiology = case_when(
           nguyennhan == 1 ~ "Triglycerid",
           nguyennhan == 2 ~ "Alcohol",
           nguyennhan == 3 ~ "Gallstones",
           TRUE ~ "Unknown"
         ),
         lv_bisap = case_when(
           lvbisap == 0 ~ "<3",
           TRUE ~ ">=3"
         ),
         sex = case_when(
           gioi == 0 ~ "Female",
           TRUE ~ "Male"
         ),
         pe = case_when(
           tdmp == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         hbp = case_when(
           tha == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         diabetes = case_when(
           dtd == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         pseudocyst = case_when(
           nanggia == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         necrosis = case_when(
           hoaitutuy == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         fluid = case_when(
           tudich == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         necrosis_wall = case_when(
           hoaituwall == 0 ~ "No",
           TRUE ~ "Yes"
         ),
         mortality = case_when(
           ketcuoc == 0 ~ "No",
           TRUE ~ "Yes"
         )) %>% 
  rename(age = tuoi,
         sap = phando2) %>% 
  select(sap, sex, age, pe, bun, bisap, lv_bisap, etiology, 
         hbp, diabetes, pseudocyst, necrosis, fluid, necrosis_wall,
         mortality, lym, wbc, hct, lipase, neu, cre, amylase,
         tri, ctsi, crp, plt) 

external <- external[1:100,]
```

```{r}
df <- rbind(train, test, external)

df <- df %>% 
  mutate(nci = neu*cre,
         neu_crp = neu*crp,
         plr = plt/lym,
         nlr = neu/lym,
         cpr = crp/plt,
         ncrp_plt = neu_crp/plt
         )

set.seed(123)
train_index <- createDataPartition(y = df$sap, p = 0.7, list = FALSE)

train <- df[train_index, ]
test <- df[-train_index, ]

train$type <- "Train"
test$type  <- "Test"

df <- rbind(train,test)

cols <- c("sex", "sap", "pe", "lv_bisap", "etiology",
          "hbp", "diabetes", "pseudocyst", "necrosis", "fluid", "necrosis_wall", "mortality", "type")

df[cols] <- lapply(df[cols], as.factor)
```

```{r}
fix_outlier_median <- function(x) {

  Q1 <- quantile(x, 0.25, na.rm = TRUE)
  Q3 <- quantile(x, 0.75, na.rm = TRUE)
  IQR <- Q3 - Q1

  upper_bound <- Q3 + 1.5 * IQR
  lower_bound <- Q1 - 1.5 * IQR
  
  med_val <- median(x, na.rm = TRUE)
  
  n_outliers <- sum(x > upper_bound | x < lower_bound, na.rm = TRUE)
  if (n_outliers > 0) {
    print(paste("Đã phát hiện và thay thế", n_outliers, "giá trị outlier bằng", med_val))
  }
  
  x <- ifelse(x > upper_bound | x < lower_bound, med_val, x)
  return(x)
}

train$bun_clean <- fix_outlier_median(train$bun)
test$bun_clean <- fix_outlier_median(test$bun)
```

## Descriptive summary

### Whole data

```{r}
tbl_summary(
  df,
  by = type,
  include = everything(),
  missing = "no",
  digits = c(all_continuous() ~ 1, all_categorical() ~ c(0, 1)),
  statistic =  list(all_continuous() ~ "{median} ({p25}-{p75})")
) %>%
  add_p(
    pvalue_fun = function(x)
      style_pvalue(x, digits = 3),
    test = list(
      all_continuous() ~ "wilcox.test",
      all_categorical() ~ "fisher.test"
    )
  ) %>%
  add_overall()
```

### Train by SAP

```{r}
tbl_summary(
  train,
  by = sap,
  include = everything(),
  missing = "no",
  digits = c(all_continuous() ~ 1, all_categorical() ~ c(0, 1)),
  statistic =  list(all_continuous() ~ "{median} ({p25}-{p75})")
) %>%
  add_p(
    pvalue_fun = function(x)
      style_pvalue(x, digits = 3),
    test = list(
      all_continuous() ~ "wilcox.test",
      all_categorical() ~ "fisher.test"
    )
  ) %>%
  add_overall()
```

## Distribution plots

```{r}
df_long <- train %>%
  pivot_longer(cols = c(nci, plr, nlr, bun, lym, wbc, neu, hct, cre, crp, plt, cpr),
               names_to = "variable",
               values_to = "value")

label_vars <- c(
  nci = "NCI",
  plr = "PLR",
  nlr = "NLR",
  bun = "BUN",
  lym = "Lym",
  wbc = "WBC", 
  neu = "Neu",
  hct = "HCT",
  cre = "CRE",
  crp = "CRP",
  plt = "PLT",
  cpr = "CPR"
)

ggplot(df_long, aes(x = as.factor(sap), y = value, 
                    fill = as.factor(sap))) +
  geom_violin(trim = FALSE) +
  geom_boxplot(width = 0.1,       
               fill = "white",    
               color = "black",   
               alpha = 0.8,       
               outlier.size = 0.5) + 
  stat_compare_means(aes(group = as.factor(sap)), 
                     label = "p.signif",      
                     method = "wilcox.test",  
                     hide.ns = FALSE,         
                     vjust = 0.5) +
  scale_fill_manual(name = "",
                    labels = c("0" = "Non SAP", "1" = "SAP"),
                    values = c("0" = "#2E86C1", "1" = "#F39C12")
                    ) +
  facet_wrap(~ variable, scales = "free_y", ncol = 4,
             labeller = labeller(variable = label_vars)
             ) +
  labs(x = "", y = "Values", fill = "") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "lightblue"),
        legend.position = "bottom",
        axis.title = element_text(size = 16, color = "black", face = "bold"),
        axis.text = element_text(size = 13, color = "black"),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 14, color = "black")
        )
```

## Heatmap

```{r}
df_pairs <- train %>%
  select(nci, plr, nlr, bun, lym, wbc, neu, hct, cre, crp, plt, cpr) %>% 
  rename(
    "NCI" = nci,
    "PLR" = plr,
    "NLR" = nlr,
    "BUN" = bun,
    "Lym" = lym,
    "WBC" = wbc,
    "Neu" = neu, 
    "HCT" = hct,
    "Creatinine" = cre,
    "CRP" = crp,
    "PLT" = plt,
    "CPR" = cpr
  )

corr_matrix <- cor(df_pairs, 
                   method = "spearman", 
                   use = "pairwise.complete.obs")

ggcorrplot(corr_matrix, 
           method = "square",       
           type = "lower",         
           lab = TRUE,              
           lab_size = 3,            
           p.mat = cor_pmat(df_pairs), 
           sig.level = 0.05,       
           insig = "blank",         
           hc.order = TRUE,    
           colors = c("#6D9EC1", "white", "#E46726"), 
           ggtheme = ggplot2::theme_dark()) +
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1, size = 12, color = "black"),
    axis.text.y = element_text(size = 12, color = "black"),
    legend.text = element_text(size = 14, color = "black")
  ) +
  labs(x = "", y = "")
```

## Build models

### Train models

```{r}
set.seed(234)
train$sap <- factor(train$sap, levels = c(0, 1), labels = c("nonsap", "sap"))
test$sap <- factor(test$sap, levels = c(0, 1), labels = c("nonsap", "sap"))

kfold <- trainControl(method = "cv",
                      number = 10,
                      savePredictions = "all",
                      classProbs = TRUE)

pos_class <- "sap" 

# Combined Model
m1 <- train(sap ~ bun_clean + wbc + crp, data = train,
                method = "glm", family = "binomial", 
                trControl = kfold)

# BUN
m2 <- train(sap ~ bun_clean, data = train,
                method = "glm", family = "binomial", 
                trControl = kfold)

# WBC
m3 <- train(sap ~ wbc, data = train,
                method = "glm", family = "binomial", 
                trControl = kfold)

# CRP
m4 <- train(sap ~ crp, data = train,
                method = "glm", family = "binomial", 
                trControl = kfold)

# BISAP
m5 <- train(sap ~ bisap, data = train,
                method = "glm", family = "binomial", 
                trControl = kfold)
```

### Fit models

```{r}
get_prob <- function(model, data) {
  predict(model, newdata = data, type = "prob")[, pos_class]
}

prob_m1 <- get_prob(m1, test)
prob_m2  <- get_prob(m2, test)
prob_m3  <- get_prob(m3, test)
prob_m4  <- get_prob(m4, test)
prob_m5 <- get_prob(m5, test)

roc_m1 <- roc(test$sap, prob_m1, quiet = TRUE)
roc_m2  <- roc(test$sap, prob_m2, quiet = TRUE)
roc_m3  <- roc(test$sap, prob_m3, quiet = TRUE)
roc_m4  <- roc(test$sap, prob_m4, quiet = TRUE)
roc_m5  <- roc(test$sap, prob_m5, quiet = TRUE)
```

### ROC Curves

```{r}
size_text_roc <- 4
x_text_roc <- 0.65
y_text_roc <- 0.25
roc.list <- list(roc_m1, roc_m2, roc_m3, roc_m4)
ggroc(roc.list, aes = "color", size = 1, linetype = "solid", legacy.axes = TRUE) +
    annotate("text", x = x_text_roc, y = y_text_roc, size = size_text_roc, hjust = 0, 
             color = "#1f77b4",
             label = paste0("BUN + WBC + CRP = ", sprintf("%.3f", roc_m1$auc))) +
    annotate("text", x = x_text_roc, y = y_text_roc - 0.1, size = size_text_roc, hjust = 0, 
             color = "#ff7f0e",
             label = paste0("BUN = ", sprintf("%.3f", roc_m2$auc))) +
    annotate("text", x = x_text_roc, y = y_text_roc - 0.2, size = size_text_roc, hjust = 0, 
             color = "#d340a2",
             label = paste0("WBC = ", sprintf("%.3f", roc_m3$auc))) +
  annotate("text", x = x_text_roc, y = y_text_roc - 0.3, size = size_text_roc, hjust = 0, 
             color = "#d340a2",
             label = paste0("CRP = ", sprintf("%.3f", roc_m4$auc))) +
    geom_segment(aes(x = 0, xend = 1, y = 0, yend = 1),
                 color = "darkgrey", linetype = "dashed", size = 0.8) +  # Đường y=x
    theme_classic() +
    theme(text = element_text(size = 16),
          legend.position = "none",
          legend.title = element_blank(),
          legend.text = element_text(size = 18,
                                     color = "black"),
          axis.text = element_text(size = 18,
                                   color = "black"),
          axis.title = element_text(size = 20,
                                   color = "black")) +
    scale_color_bmj(name = "Models", 
labels = c("BUN + WBC + CRP", "BUN", "WBC", "CRP")) +
    labs(x = "1 - Specificity", y = "Sensitivity")
```

### Compare ROC curves

```{r}
set.seed(123)
roc.test(roc_m1, roc_m2, method="bootstrap", boot.n=1000)
roc.test(roc_m1, roc_m3, method="bootstrap", boot.n=1000)
roc.test(roc_m1, roc_m4, method="bootstrap", boot.n=1000)
```

## VIF

```{r}
vif_val <- vif(m1$finalModel)

vif_df <- data.frame(
  Variable = names(vif_val),
  VIF = as.numeric(vif_val)
)

vif_df <- vif_df %>% 
  mutate(Variable = case_when(
    Variable == "bun_clean" ~ "BUN",
    Variable == "wbc" ~ "WBC",
    TRUE ~ "CRP"
  ))

p1 <- ggplot(vif_df, aes(x = reorder(Variable, VIF), y = VIF)) +
  geom_col(width = 0.6, fill = "#4E84C4", alpha = 0.9) + 
  geom_hline(yintercept = 2, linetype = "dashed", color = "red", size = 0.8) + 
  coord_flip() + 
  theme_bw(base_size = 14) + 
  labs(
    x = NULL,
    y = "Variance Inflation Factor (VIF)"
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    plot.title = element_text(face = "bold", hjust = 0.5),
    plot.subtitle = element_text(hjust = 0.5, color = "gray30"),
    axis.text = element_text(color = "black")
  ) +

  geom_text(aes(label = round(VIF, 2)), hjust = -0.2, size = 4) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15)))

p1
```

## SHAP value

```{r}
X_shap <- train %>% select(bun_clean, wbc, crp) 

pfun <- function(object, newdata) {
  predict(object, newdata = newdata, type = "prob")[, 2] 
}

shap_raw <- explain(m1, X = X_shap, pred_wrapper = pfun, nsim = 100)

shp_viz <- shapviz(shap_raw, X = X_shap)

names(shp_viz$X) <- c("BUN", "WBC", "CRP")

colnames(shp_viz$S) <- c("BUN", "WBC", "CRP")

p2 <- sv_importance(shp_viz, kind = "beeswarm") +
  theme_bw(base_size = 14) + 
  scale_color_gradient(low = "#3A0CA3", high = "#F72585", 
                       name = "Feature Value") + 
  labs(
    x = "SHAP values",
    y = NULL
  ) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "grey50") + 
  theme(
    plot.title = element_text(face = "bold", hjust = 0.5),
    legend.position = "right",
    panel.grid.minor = element_blank(),
    axis.text = element_text(color = "black")
  )

p2
```

```{r}
p1 / p2 + 
  plot_annotation(tag_levels = 'A')
```

## Calculate metrics

```{r}
rets <- c("threshold", "specificity", "sensitivity", "accuracy", "npv", "ppv")

ci.coords(roc_m1, x = "best", ret = rets,
          best.policy = "random")

ci.coords(roc_m2, x = "best", ret = rets, 
          best.policy = "random")

ci.coords(roc_m3, x = "best", ret = rets,
          best.policy = "random")
```

## Nomogram

```{r}
label(train$bun_clean) <- "BUN (mg/dL)"

label(train$wbc)       <- "WBC (G/L)"

label(train$crp)       <- "CRP (mg/L)"

dd <- datadist(train)
options(datadist = "dd")
fit_final <- lrm(sap ~ bun_clean + wbc + crp, 
                 data = train, x = TRUE, y = TRUE)

my_cuts <- c(0.01, 0.05, seq(0.1, 0.9, by = 0.2), 0.95, 0.99, 0.999)

nom <- nomogram(fit_final, 
                fun = plogis,
                fun.at = my_cuts, # Dùng dải mốc mới này
                lp = FALSE, 
                funlabel = "Risk of Severe Acute Pancreatitis")

# Vẽ lại
plot(nom, xfrac = 0.5, cex.axis = 0.8, lwd = 2)
```

## Calibration combined model

```{r}
y_test_numeric <- as.numeric(test$sap) - 1 
pred_probs_test <- predict(fit_final, newdata = test, type = "fitted")

validation_plot <- val.prob(p = pred_probs_test, 
                            y = y_test_numeric, 
                            m = 20,
                            cex = 0.8,       
                            xlab = "Predicted Probability",
                            ylab = "Observed Proportion")
```

## Compare BISAP

### ROC Curves

```{r}
size_text_roc <- 4
x_text_roc <- 0.65
y_text_roc <- 0.25
roc.list <- list(roc_m1, roc_m5)
ggroc(roc.list, aes = "color", size = 1, linetype = "solid", legacy.axes = TRUE) +
    annotate("text", x = x_text_roc, y = y_text_roc, size = size_text_roc, hjust = 0, 
             color = "#1f77b4",
             label = paste0("BUN + WBC + CRP = ", sprintf("%.3f", roc_m1$auc))) +
    annotate("text", x = x_text_roc, y = y_text_roc - 0.1, size = size_text_roc, hjust = 0, 
             color = "#ff7f0e",
             label = paste0("BISAP = ", sprintf("%.3f", roc_m5$auc))) +
    geom_segment(aes(x = 0, xend = 1, y = 0, yend = 1),
                 color = "darkgrey", linetype = "dashed", size = 0.8) +  # Đường y=x
    theme_classic() +
    theme(text = element_text(size = 16),
          legend.position = "none",
          legend.title = element_blank(),
          legend.text = element_text(size = 18,
                                     color = "black"),
          axis.text = element_text(size = 18,
                                   color = "black"),
          axis.title = element_text(size = 20,
                                   color = "black")) +
    scale_color_bmj(name = "Models", 
labels = c("BUN + WBC + CRP", "BISAP")) +
    labs(x = "1 - Specificity", y = "Sensitivity")
```

### Roc test

```{r}
roc.test(roc_m1, roc_m5, method="bootstrap", boot.n=1000)
```

## Decision curves

```{r}
df_plot <- test[,c("sap","bun_clean","wbc", "crp")]
df_plot <- na.omit(df_plot)
pred1 <- predict(m1, newdata = df_plot, type = 'prob')
df_plot$pred1 <- pred1[,2]
df_plot$sap <- as.numeric(df_plot$sap) - 1
dca_obj <- dca(sap ~ pred1,
    data = df_plot,
    label = list(pred1 = "BUN + WBC + CRP"))

dca_df <- dca_obj$dca  %>%
  select(variable, threshold, net_benefit)

benefit_bar_df <- function(df, bar_start = -0.02, bar_width = 0.015,
                           x_min = NULL, x_max = NULL,
                           strict = FALSE, tol = 1e-8) {
  
  vars <- unique(df$variable)
  var_all  <- vars[grep("^all$", vars, ignore.case = TRUE)][1]
  var_none <- vars[grep("^none$", vars, ignore.case = TRUE)][1]
  var_model <- setdiff(vars, c(var_all, var_none))[1] 

  w <- df |>
    select(threshold, variable, net_benefit) |>
    pivot_wider(names_from = variable, values_from = net_benefit) |>
    arrange(threshold) |>
    distinct(threshold, .keep_all = TRUE) |>
    rename(a = !!var_all, n = !!var_none, f = !!var_model)

  t <- w$threshold; a <- w$a; n <- w$n; f <- w$f
  
  if (is.null(x_min)) x_min <- min(t, na.rm = TRUE)
  if (is.null(x_max)) x_max <- max(t, na.rm = TRUE)

  inter <- function(x, y1, y2) {
    out <- numeric(0)
    for (i in seq_len(length(x) - 1)) {
      x0 <- x[i]; x1 <- x[i + 1]
      if (x1 < x_min || x0 > x_max) next
      d0 <- y1[i] - y2[i]; d1 <- y1[i + 1] - y2[i + 1]
      if (!is.finite(d0) || !is.finite(d1)) next
      if (d0 * d1 <= 0) {
        denom <- (y1[i + 1] - y1[i]) - (y2[i + 1] - y2[i])
        cand <- if (denom == 0) c(x0, x1) else x0 + (y2[i] - y1[i]) * (x1 - x0) / denom
        out <- c(out, cand)
      }
    }
    sort(unique(out[out >= x_min & out <= x_max & is.finite(out)]))
  }

  br <- sort(unique(c(x_min, inter(t,f,a), inter(t,f,n), inter(t,a,n), x_max)))

  mids <- (br[-length(br)] + br[-1]) / 2
  
  fm <- approx(t, f, xout = mids, rule = 2)$y
  am <- approx(t, a, xout = mids, rule = 2)$y
  nm <- approx(t, n, xout = mids, rule = 2)$y
  
  comp <- if (strict) `>` else `>=`
  
  win <- comp(fm, am) & comp(fm, nm)

  out <- tibble(
    threshold_start = br[-length(br)],
    threshold_end   = br[-1],
    benefit         = ifelse(win, "Benefit", "No Benefit"), 
    bar_start       = bar_start,
    bar_width       = bar_width
  ) |>
    filter(threshold_end - threshold_start > tol) |>
    arrange(threshold_start) |>
    mutate(grp = cumsum(benefit != lag(benefit, default = first(benefit))) ) |>
    group_by(grp, benefit) |>
    summarise(
      threshold_start = min(threshold_start),
      threshold_end   = max(threshold_end),
      bar_start       = first(bar_start),
      bar_width       = first(bar_width),
      .groups = "drop"
    )

  out
}

bar_df <- benefit_bar_df(dca_df, x_min = 0, x_max = 1) 

bar_df_lab <- bar_df %>% 
    dplyr::mutate(
        x = (threshold_start + threshold_end) / 2,
        y = bar_start - bar_width / 2,
        label = ifelse(benefit == "Benefit", "Benefit", NA)
    )

plot(dca_obj) +
  
    coord_cartesian(xlim = c(0, 1), ylim = c(-0.035, 0.23), expand = FALSE) +
    
    geom_rect(data = bar_df,
              aes(xmin = threshold_start, xmax = threshold_end, 
                  ymin = bar_start - bar_width, ymax = bar_start, 
                  fill = benefit), 
              inherit.aes = FALSE, show.legend = FALSE) +
    geom_text(
        data = bar_df_lab,
        aes(x = x, y = y, label = label),
        inherit.aes = FALSE,
        fontface = "bold", size = 3.5, vjust = 0.5, hjust = 0.5,
        color = "white", check_overlap = TRUE
    ) +

    scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
    scale_fill_manual(values = c("Benefit" = "#00BFC4", "No Benefit" = "#F8766D")) +
    theme_classic()
```








